name: drivercash
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.31.0       # ✅ Compatível com FlutterLab
  firebase_auth: ^4.17.0       # ✅ OK
  cloud_firestore: ^4.15.0     # ✅ OK
  firebase_storage: ^11.7.7    # ✅ Compatível com firebase_core 2.x
  charts_flutter: ^0.12.0      # ✅ Gráficos compatíveis
  firebase_analytics: ^10.10.7
  firebase_database: ^10.5.7
  fl_chart: ^0.66.0
  git: ^2.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
     - lib/assets/images/logodrivercash.jpg
     - lib/assets/images/drivercash.png

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
